# Generated by Django 4.1.3 on 2022-11-18 18:08

from django.db import migrations, models

<<<<<<< HEAD

=======
>>>>>>> d8c2f76c084e8a49f5f598379d3c7602a1931f13
class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
<<<<<<< HEAD
    ]
=======
    ]
>>>>>>> d8c2f76c084e8a49f5f598379d3c7602a1931f13
